"""add site_id to ScheduledPost

Revision ID: 5fccc3f2a78b
Revises: c1c5575fd1ef
Create Date: 2025-04-07 20:35:49.772711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fccc3f2a78b'
down_revision = 'c1c5575fd1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.drop_column('site_id')

    # ### end Alembic commands ###
